### ISSUE TITLE
Fail to find conventional commit ended by pull request number with round brackets

### ISSUE THREAD

**Issue by martinku-tw** [dev-build-deploy/release-me#24]
## Context
When merging a github pull request, the default commit message contains the pull request number with round brackets in the end. And it can't be found during retrieving conventional commits.
Here is an example:
```
feat(login): add support google oauth (#12)
```
## Proposal
Fix conventional commit matching implementation to support commit with round brackets in description.

**Comment by Kevin-de-Jong** [comment]
Hi @martinku-tw; thanks for reporting this issue :100:.
I will have a look and report back to you soon :tm:

**Comment by Kevin-de-Jong** [comment]
Addressed with [Release v0.12.1](https://github.com/dev-build-deploy/release-me/releases/tag/v0.12.1).
Feel free to let me know whether this is working as expected on your end.
